Improves retries backoff for network errors
SiftScience/sift-ios pull request #151
Opened 2024-07-02 12:33 UTC by iprysiazhnyi-sift

## Purpose
Backoff strategy for network errors should be different to HTTP errors

## Summary
Set hard limit for no more than 1 minute in retries for network errors. It will be no exponential backoff strategy for such errors, just retries with base backoff delay

## Testing
Local testing and unit tests

## Checklist
- [ ] The change was thoroughly tested manually
- [ ] The change was covered with unit tests
- [ ] The change was tested with the integration example
- [ ] Necessary changes were made in the integration example (if applicable)
- [ ] New functionality is reflected in README (if applicable)

2024-07-02 15:43 UTC, mpierotti-sift requested changes

2024-07-02 15:43 UTC, mpierotti-sift commented on Sift/SiftUploader.m
> +- (void)retryUploadWithDelay:(NSTimeInterval)delay {
I like that you extracted this method.

2024-07-02 15:43 UTC, mpierotti-sift commented on Sift/SiftUploader.m
> +// Drop a batch if our backend has rejected it `SF_REJECT_LIMIT` times.
Could you update this comment to refer to the network error limits instead?

2024-07-02 15:43 UTC, mpierotti-sift commented on Sift/SiftUploader.m
> +static const int64_t SF_DEFAULT_NETWORK_MAX_RETRIES = 60;
This seems odd because the actual default will be max_delay / backoff (which is 12). Should this be 12 instead? I would rename this to `SF_FALLBACK_NETWORK_MAX_RETRIES`.

2024-07-02 15:43 UTC, mpierotti-sift commented on Sift/SiftUploader.m
> +static const int64_t SF_NETWORK_MAX_DELAY_IN_SEC = 60 * NSEC_PER_SEC;
Should this be higher? As I understand it, the current logic in this PR is to retry every 5 seconds for up to a minute. Ideally I think we would do an increasing backoff, and retry for longer. (Forgive me if we covered this in our internal discussion) Hypothetically the current logic will mean that we won't send these events if the network is unavailable for 1 minute, whereas previously we would be tolerant of indefinite network issues.

2024-07-04 12:00 UTC, iprysiazhnyi-sift commented on Sift/SiftUploader.m
> +static const int64_t SF_DEFAULT_NETWORK_MAX_RETRIES = 60;
yeah, probably `default` is not a proper word here, the `fallback` looks better. Idea is to set this number of max retries in case of bad calculation to have stop limit

2024-07-04 12:03 UTC, iprysiazhnyi-sift commented on Sift/SiftUploader.m
> +static const int64_t SF_NETWORK_MAX_DELAY_IN_SEC = 60 * NSEC_PER_SEC;
From what I recall we discussed that it should not have an indefinite retries as it was before and limit network retries in time. Probably we need to discuss it internally again to agreed on final solution

2024-07-09 13:15 UTC, sbogolii-sift approved these changes
Great work! LGTM!

2024-07-09 14:28 UTC, mpierotti-sift approved these changes
LGTM

2024-07-09 15:47 UTC, merged